name: jacob
description: Jacob` backend.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

dependencies:
  vaden: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.14
  vaden_class_scanner: ^1.0.0
