openapi:
  title: Vaden Generator API
  version: 1.0.0
  description: API para a página de geração de projeto do Vaden.

server:
  port: 8080
  host: localhost

storage:
  provider: local  
  local:
    folder: './uploads'
